/**
 * @fileoverview gRPC-Web generated client stub for notification
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.1
// source: notification.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('./google/api/annotations_pb.js')

var auth_pb = require('./auth_pb.js')
const proto = {};
proto.notification = require('./notification_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.notification.NotificationServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.notification.NotificationServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.notification.ListNotificationsRequest,
 *   !proto.notification.Notifications>}
 */
const methodDescriptor_NotificationService_ListNotifications = new grpc.web.MethodDescriptor(
  '/notification.NotificationService/ListNotifications',
  grpc.web.MethodType.UNARY,
  proto.notification.ListNotificationsRequest,
  proto.notification.Notifications,
  /**
   * @param {!proto.notification.ListNotificationsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.notification.Notifications.deserializeBinary
);


/**
 * @param {!proto.notification.ListNotificationsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.notification.Notifications)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.notification.Notifications>|undefined}
 *     The XHR Node Readable Stream
 */
proto.notification.NotificationServiceClient.prototype.listNotifications =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/notification.NotificationService/ListNotifications',
      request,
      metadata || {},
      methodDescriptor_NotificationService_ListNotifications,
      callback);
};


/**
 * @param {!proto.notification.ListNotificationsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.notification.Notifications>}
 *     Promise that resolves to the response
 */
proto.notification.NotificationServicePromiseClient.prototype.listNotifications =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/notification.NotificationService/ListNotifications',
      request,
      metadata || {},
      methodDescriptor_NotificationService_ListNotifications);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.notification.MarkAsReadRequest,
 *   !proto.auth.Confirmation>}
 */
const methodDescriptor_NotificationService_MarkAsRead = new grpc.web.MethodDescriptor(
  '/notification.NotificationService/MarkAsRead',
  grpc.web.MethodType.UNARY,
  proto.notification.MarkAsReadRequest,
  auth_pb.Confirmation,
  /**
   * @param {!proto.notification.MarkAsReadRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  auth_pb.Confirmation.deserializeBinary
);


/**
 * @param {!proto.notification.MarkAsReadRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.Confirmation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.Confirmation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.notification.NotificationServiceClient.prototype.markAsRead =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/notification.NotificationService/MarkAsRead',
      request,
      metadata || {},
      methodDescriptor_NotificationService_MarkAsRead,
      callback);
};


/**
 * @param {!proto.notification.MarkAsReadRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.Confirmation>}
 *     Promise that resolves to the response
 */
proto.notification.NotificationServicePromiseClient.prototype.markAsRead =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/notification.NotificationService/MarkAsRead',
      request,
      metadata || {},
      methodDescriptor_NotificationService_MarkAsRead);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.notification.EmptyRequest,
 *   !proto.auth.Confirmation>}
 */
const methodDescriptor_NotificationService_MarkAllAsRead = new grpc.web.MethodDescriptor(
  '/notification.NotificationService/MarkAllAsRead',
  grpc.web.MethodType.UNARY,
  proto.notification.EmptyRequest,
  auth_pb.Confirmation,
  /**
   * @param {!proto.notification.EmptyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  auth_pb.Confirmation.deserializeBinary
);


/**
 * @param {!proto.notification.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.Confirmation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.Confirmation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.notification.NotificationServiceClient.prototype.markAllAsRead =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/notification.NotificationService/MarkAllAsRead',
      request,
      metadata || {},
      methodDescriptor_NotificationService_MarkAllAsRead,
      callback);
};


/**
 * @param {!proto.notification.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.Confirmation>}
 *     Promise that resolves to the response
 */
proto.notification.NotificationServicePromiseClient.prototype.markAllAsRead =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/notification.NotificationService/MarkAllAsRead',
      request,
      metadata || {},
      methodDescriptor_NotificationService_MarkAllAsRead);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.notification.DeleteNotificationRequest,
 *   !proto.auth.Confirmation>}
 */
const methodDescriptor_NotificationService_DeleteNotification = new grpc.web.MethodDescriptor(
  '/notification.NotificationService/DeleteNotification',
  grpc.web.MethodType.UNARY,
  proto.notification.DeleteNotificationRequest,
  auth_pb.Confirmation,
  /**
   * @param {!proto.notification.DeleteNotificationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  auth_pb.Confirmation.deserializeBinary
);


/**
 * @param {!proto.notification.DeleteNotificationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.Confirmation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.Confirmation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.notification.NotificationServiceClient.prototype.deleteNotification =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/notification.NotificationService/DeleteNotification',
      request,
      metadata || {},
      methodDescriptor_NotificationService_DeleteNotification,
      callback);
};


/**
 * @param {!proto.notification.DeleteNotificationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.Confirmation>}
 *     Promise that resolves to the response
 */
proto.notification.NotificationServicePromiseClient.prototype.deleteNotification =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/notification.NotificationService/DeleteNotification',
      request,
      metadata || {},
      methodDescriptor_NotificationService_DeleteNotification);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.notification.EmptyRequest,
 *   !proto.auth.Confirmation>}
 */
const methodDescriptor_NotificationService_ClearAll = new grpc.web.MethodDescriptor(
  '/notification.NotificationService/ClearAll',
  grpc.web.MethodType.UNARY,
  proto.notification.EmptyRequest,
  auth_pb.Confirmation,
  /**
   * @param {!proto.notification.EmptyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  auth_pb.Confirmation.deserializeBinary
);


/**
 * @param {!proto.notification.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.Confirmation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.Confirmation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.notification.NotificationServiceClient.prototype.clearAll =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/notification.NotificationService/ClearAll',
      request,
      metadata || {},
      methodDescriptor_NotificationService_ClearAll,
      callback);
};


/**
 * @param {!proto.notification.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.Confirmation>}
 *     Promise that resolves to the response
 */
proto.notification.NotificationServicePromiseClient.prototype.clearAll =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/notification.NotificationService/ClearAll',
      request,
      metadata || {},
      methodDescriptor_NotificationService_ClearAll);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.notification.StreamRequest,
 *   !proto.notification.Notification>}
 */
const methodDescriptor_NotificationService_StreamNotifications = new grpc.web.MethodDescriptor(
  '/notification.NotificationService/StreamNotifications',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.notification.StreamRequest,
  proto.notification.Notification,
  /**
   * @param {!proto.notification.StreamRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.notification.Notification.deserializeBinary
);


/**
 * @param {!proto.notification.StreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.notification.Notification>}
 *     The XHR Node Readable Stream
 */
proto.notification.NotificationServiceClient.prototype.streamNotifications =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/notification.NotificationService/StreamNotifications',
      request,
      metadata || {},
      methodDescriptor_NotificationService_StreamNotifications);
};


/**
 * @param {!proto.notification.StreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.notification.Notification>}
 *     The XHR Node Readable Stream
 */
proto.notification.NotificationServicePromiseClient.prototype.streamNotifications =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/notification.NotificationService/StreamNotifications',
      request,
      metadata || {},
      methodDescriptor_NotificationService_StreamNotifications);
};


module.exports = proto.notification;

